/**
 * Auto-generated by Wally (built on libretto MIT primitives)
 * Recorded: 2026-09-04T10:20:37.107Z
 * Actions: 60
 * Pages: zor-frontend.pages.dev, ext:dlcobpji
 * Extension: detected (dlcobpji)
 * Run: node playwright.spec.js  (needs Chrome with --remote-debugging-port=9222 and Profile 9)
 */
const { chromium } = require('playwright');
const assert = require('assert');

const CDP_URL = 'http://127.0.0.1:9222';

(async () => {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const contexts = browser.contexts();
  const context = contexts.find(c => c.pages().length > 0) || contexts[0];
  let page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
  let extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  await page.goto('https://zor-frontend.pages.dev/', { waitUntil: 'networkidle', timeout: 30000 });
  await page.waitForTimeout(3000);
  await page.getByRole('button', { name: /Connect Wallet/i }).first().click({ timeout: 5000 });
  await page.waitForTimeout(1000);
  await page.locator('div > div > p').first().click({ force: true, timeout: 5000 });
  await page.waitForTimeout(1000);

  // Switch to extension page (any chrome-extension:// URL)
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    // Wait for extension to open (triggered by prior page click)
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      console.log('[Wally] Waiting for extension popup...', i);
      await page.waitForTimeout(1000);
    }
  }
  if (extPage) {
    await extPage.bringToFront().catch(() => {});
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(1500);
    console.log('[Wally] Extension visible:', extPage.url());
    await extPage.locator('[data-testid="cambiar-red-button"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.locator('[data-testid="Clever Carrot"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('[data-testid="Clever Carrot"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('[data-testid="conectar-button"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/account/tokens', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    // Wallet connected: starknet (0x02eaa076636635fa983094d7a8e367293973c3263c2310586a2579c1d4fe8b71)
    await page.waitForTimeout(2000);
    await extPage.locator('input[name="example.com"]').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('input[name="example.com"]').fill('naiamstudio.com');
    await page.waitForTimeout(500);
    await extPage.locator('input[name="example.com"]').fill('naiamstudio.com');
    await page.waitForTimeout(500);
    await extPage.getByRole('button', { name: /💳 PAY 0\.0300 STRK & BROWSE/i }).first().click({ timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.getByRole('button', { name: /SEND 0\.0300 STRK & ACTIVATE/i }).first().click({ timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/accounts/verify/email?returnPath=%2Faccount%2Ftokens', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.locator('[data-testid="navigation-bar-close-button"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('[data-testid="cancel"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/account/tokens', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.locator('div:nth-child(1) > div > div:nth-child(2)').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('div:nth-child(1) > div > div:nth-child(2)').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
  }
  console.log('[Wally] Replay done, final URL:', page.url());
  if (extPage) {
    console.log('[Wally] Extension final URL:', extPage.url());
    await extPage.bringToFront().catch(() => {});
  } else {
    await page.bringToFront().catch(() => {});
  }
  console.log('[Wally] Keeping browser open 10s for visual check...');
  await page.waitForTimeout(10000);
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
