import { describe, it, expect } from 'vitest';
import { generatePlaywrightTest } from '../lib/generate-test.js';

describe('generatePlaywrightTest', () => {
  it('throws on empty actions', () => {
    expect(() => generatePlaywrightTest([])).toThrow('No actions provided');
  });

  it('throws on null actions', () => {
    expect(() => generatePlaywrightTest(null)).toThrow('No actions provided');
  });

  it('generates valid Playwright code with navigate action', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Auto-generated by Wally');
    expect(test).toContain('chromium.connectOverCDP');
    expect(test).toContain("await page.goto('https://example.com'");
    expect(test).toContain('Actions: 1');
    expect(test).toContain('Pages: main');
  });

  it('generates code with click action', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
      { ts: '2024-01-01T00:00:01.000Z', type: 'click', selector: '#submit-btn', text: 'Submit' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain("await page.goto('https://example.com'");
    expect(test).toContain('#submit-btn');
    expect(test).toContain('Actions: 2');
  });

  it('generates code with fill action', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
      { ts: '2024-01-01T00:00:01.000Z', type: 'fill', selector: '#email', value: 'test@example.com' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('#email');
    expect(test).toContain('test@example.com');
  });

  it('handles extension actions', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
      { ts: '2024-01-01T00:00:01.000Z', type: 'click', selector: '[data-testid="connect"]', page: 'ext:wallet' },
      { ts: '2024-01-01T00:00:02.000Z', type: 'click', selector: '#approve', page: 'ext:wallet' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('extPage');
    expect(test).toContain('chrome-extension://');
    expect(test).toContain('Switch to extension page');
  });

  it('detects extension ID from chrome-extension:// URL', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'chrome-extension://abcdefghijklmnop/index.html' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Extension: detected');
    expect(test).toContain('abcdefghijklmnop');
  });

  it('includes network capture when option is set', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
    ];

    const test = generatePlaywrightTest(actions, { includeNetwork: true });

    // The function doesn't currently use includeNetwork in the generated code,
    // but the option should be accepted without error
    expect(test).toContain('Auto-generated by Wally');
  });

  it('handles multiple pages', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com', page: 'main' },
      { ts: '2024-01-01T00:00:01.000Z', type: 'navigate', url: 'https://other.com', page: 'tab2' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Pages: main, tab2');
  });

  it('generates proper closing code', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Replay done, final URL');
    expect(test).toContain('browser.close()');
    expect(test).toContain('process.exit(1)');
  });

  it('handles extension_connect action type', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'navigate', url: 'https://example.com' },
      { ts: '2024-01-01T00:00:01.000Z', type: 'extension_connect', extensionType: 'starknet', account: '0x123' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Extension connected: starknet');
  });

  it('escapes single quotes in fill values', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'fill', selector: '#input', value: "it's a test" },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain("it\\'s a test");
  });

  it('skips password click if not visible', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'click', selector: 'input[type="password"]' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Skip password click not visible');
  });

  it('makes data-testid clicks optional', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'click', selector: '[data-testid="unlock"]' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('Skip not visible');
  });

  it('handles text-based button selectors', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'click', selector: 'button "OK"' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('getByRole');
    expect(test).toContain('Skip optional button');
  });

  it('handles regular button selectors with error handling', () => {
    const actions = [
      { ts: '2024-01-01T00:00:00.000Z', type: 'click', selector: 'button "Connect Wallet"' },
    ];

    const test = generatePlaywrightTest(actions);

    expect(test).toContain('getByRole');
    expect(test).toContain('Click failed (continuing)');
  });
});
