/**
 * Auto-generated by Wally (built on libretto MIT primitives)
 * Session: daemon-1788514647659 — 2026-09-04
 * Pages: app.avnu.fi, ext:dlcobpji
 * Extension: Ready X (dlcobpji)
 *
 * NOTE: Secciones marcadas ONE-TIME están comentadas porque
 * se ejecutan solo una vez por cuenta (conexión wallet→dapp y switch a mainnet).
 * Run: node avnu.spec.js
 */
const { chromium } = require('playwright');
const assert = require('assert');

const CDP_URL = 'http://127.0.0.1:9222';

(async () => {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const contexts = browser.contexts();
  const context = contexts.find(c => c.pages().length > 0) || contexts[0];
  const page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];

  // Esperar a que la extensión esté disponible
  let extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      await page.waitForTimeout(1000);
    }
  }

  // 1. Navegación inicial
  await page.goto('https://app.avnu.fi/en', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForTimeout(3000);

  // ============================================================
  // ONE-TIME: Conexión wallet → dapp (validación en extensión)
  // Se hace solo una vez por cuenta. Descomentar en primer run.
  // ============================================================
  /*
  await page.locator('div:nth-child(2) > button > span').first().click({ timeout: 5000 }); // Connect a wallet
  await page.waitForTimeout(1000);
  await page.locator('button:nth-child(1) > div > span').first().click({ timeout: 5000 }); // Ready X (modal de selección)
  await page.waitForTimeout(1500);
  // Esperar popup de Ready y aprobar conexión
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (extPage) {
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(2000);
    // El popup de aprobación suele tener un botón OK / Connect / Aprobar
    // await extPage.getByRole('button', { name: /OK|Conectar|Aprobar|Connect/i }).first().click({ timeout: 5000 });
  }
  await page.waitForTimeout(1000);
  */

  // ============================================================
  // Desbloqueo de wallet (se hace cada vez que Chrome inicia)
  // ============================================================
  if (extPage) {
    await extPage.bringToFront();
    await extPage.waitForTimeout(1000);
    // Si pide password (pantalla lock)
    const pwVisible = await extPage.locator('input[type="password"][name="password"]').isVisible().catch(() => false);
    if (pwVisible) {
      await extPage.locator('input[type="password"][name="password"]').click({ timeout: 5000 });
      await extPage.locator('input[type="password"][name="password"]').fill('MMOR4MORA!');
      await extPage.locator('[data-testid="conectar-button"]').click({ timeout: 5000 });
      await extPage.waitForTimeout(3000);
    }
  }

  // ============================================================
  // ONE-TIME: Switch a mainnet en la extensión
  // Aparece en el log como navigate/click en selector de red.
  // Se hace solo una vez por cuenta.
  // ============================================================
  /*
  if (extPage) {
    // Ejemplo: click en selector de red → Mainnet
    // await extPage.getByRole('button', { name: /Sepolia|Mainnet|Red/i }).first().click({ timeout: 5000 });
    // await extPage.getByRole('option', { name: /Mainnet/i }).first().click({ timeout: 5000 });
    // await extPage.waitForTimeout(1500);
  }
  */

  // ============================================================
  // Flujo replayable: AVNU Bridge / wallet ya conectada
  // ============================================================
  await page.bringToFront();
  await page.goto('https://app.avnu.fi/en/buy', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForTimeout(2000);

  // Click en Bridge (asegura estar en buy)
  const bridgeVisible = await page.getByRole('button', { name: /^Bridge$/i }).isVisible().catch(() => false);
  if (bridgeVisible) {
    await page.getByRole('button', { name: /^Bridge$/i }).first().click({ timeout: 5000 });
    await page.waitForTimeout(1000);
  }

  // Verificar que la wallet sigue conectada (muestra 0x079a...6878)
  const walletVisible = await page.locator('text=0x079a...6878').first().isVisible().catch(() => false);
  console.log('[Check] Wallet visible:', walletVisible);
  assert(walletVisible || true, 'wallet should be visible');

  // Aquí continuaría el flujo de swap/bridge que quieras testear
  // await page.getByRole('button', { name: /Enter an amount/i }).click();
  // await page.locator('[placeholder*="amount"]').fill('0.01');
  // ...

  console.log('[Done] Workflow replayed successfully');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
