/**
 * Wally Generate Test — shared Playwright test generation.
 *
 * Generates standalone Playwright test scripts from recorded actions.
 * Used by both wally.js (cmdExport) and daemon.js (stop).
 */
const { CDP_URL } = require('./cdp');

/**
 * Generate a Playwright test script from recorded actions.
 *
 * @param {Array} actions - Array of action objects (from actions.jsonl)
 * @param {Object} [options]
 * @param {boolean} [options.includeNetwork=false] - Include network capture setup
 * @param {string} [options.outputDir] - Output directory for test file
 * @returns {string} Playwright test code string
 */
function generatePlaywrightTest(actions, options = {}) {
  if (!actions || actions.length === 0) {
    throw new Error('No actions provided for test generation');
  }

  // Group actions by page
  const pages = new Map();
  for (const action of actions) {
    const pageLabel = action.page || 'main';
    if (!pages.has(pageLabel)) pages.set(pageLabel, []);
    pages.get(pageLabel).push(action);
  }

  // Detect extension ID from recorded actions (if any extension was used)
  let detectedExtId = null;
  let detectedExtFullId = null;
  for (const action of actions) {
    if (action.url && action.url.includes('chrome-extension://')) {
      const m = action.url.match(/chrome-extension:\/\/([a-z]+)/);
      if (m) { detectedExtFullId = m[1]; detectedExtId = m[1].substring(0, 8); break; }
    }
  }
  if (!detectedExtFullId) {
    for (const action of actions) {
      if (action.page && action.page.startsWith('ext:')) {
        const match = action.page.match(/ext:(.+)/);
        if (match) detectedExtId = match[1];
        break;
      }
    }
  }

  let test = `/**
 * Auto-generated by Wally
 * Recorded: ${actions[0]?.ts || new Date().toISOString()}
 * Actions: ${actions.length}
 * Pages: ${Array.from(pages.keys()).join(', ')}
 * Extension: ${detectedExtId ? 'detected (' + detectedExtId + ')' : 'none detected'}
 * Run: node playwright.spec.js  (needs Chrome with --remote-debugging-port=9222 and Profile 9)
 */
const { chromium } = require('playwright');
const assert = require('assert');

const CDP_URL = '${CDP_URL}';

(async () => {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const contexts = browser.contexts();
  const context = contexts.find(c => c.pages().length > 0) || contexts[0];
  let page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
  let extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
`;

  let lastPage = 'main';
  const pageVars = {}; // track page variables by label (e.g. { 'www.instagram.com': 'page2' })
  let pageCount = 0;

  for (const action of actions) {
    const actionPage = action.page || 'main';

    // If switching to extension page, add page switch logic
    if (actionPage !== lastPage && actionPage.startsWith('ext:')) {
      test += `\n  // Switch to extension page (any chrome-extension:// URL)\n`;
      test += `  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));\n`;
      test += `  if (!extPage) {\n`;
      test += `    // Wait for extension to open (triggered by prior page click)\n`;
      test += `    for (let i = 0; i < 15; i++) {\n`;
      test += `      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));\n`;
      test += `      if (extPage) break;\n`;
      test += `      console.log('[Wally] Waiting for extension popup...', i);\n`;
      test += `      await page.waitForTimeout(1000);\n`;
      test += `    }\n`;
      test += `  }\n`;
      if (detectedExtFullId) {
        test += `  if (!extPage) {\n`;
        test += `    console.log('[Wally] Extension not auto-opened, opening as tab...');\n`;
        test += `    extPage = await context.newPage();\n`;
        test += `    await extPage.goto('chrome-extension://${detectedExtFullId}/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});\n`;
        test += `    await extPage.waitForTimeout(2000);\n`;
        test += `  }\n`;
      }
      test += `  if (extPage) {\n`;
      test += `    await extPage.bringToFront().catch(() => {});\n`;
      test += `    await extPage.waitForLoadState('domcontentloaded').catch(() => {});\n`;
      test += `    await extPage.waitForTimeout(1500);\n`;
      test += `    console.log('[Wally] Extension visible:', extPage.url());\n`;
      lastPage = actionPage;
    } else if (actionPage !== lastPage && !actionPage.startsWith('ext:')) {
      // Multi-tab: switching between different non-extension pages
      if (pageVars[actionPage]) {
        // Already have a variable for this page — just switch to it
        test += `\n    // Switch to tab: ${actionPage}\n`;
        test += `    await ${pageVars[actionPage]}.bringToFront().catch(()=>{});\n`;
      } else {
        // New page label — find or create a new tab
        pageCount++;
        const varName = `page${pageCount}`;
        pageVars[actionPage] = varName;
        test += `\n    // New tab: ${actionPage}\n`;
        test += `    let ${varName} = context.pages().find(p => p.url().includes('${actionPage}'));\n`;
        test += `    if (!${varName}) {\n`;
        test += `      ${varName} = await context.newPage();\n`;
        test += `      console.log('[Wally] Created new tab for ${actionPage}');\n`;
        test += `    }\n`;
        test += `    await ${varName}.bringToFront().catch(()=>{});\n`;
      }
      lastPage = actionPage;
    }

    const isExtAction = action.page && action.page.startsWith('ext:');
    const indent = isExtAction ? '    ' : '  ';
    const target = isExtAction ? 'extPage' : (pageVars[actionPage] || 'page');

    if (action.type === 'navigate') {
      test += `${indent}await ${target}.goto('${action.url}', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});\n`;
      test += `${indent}await ${target}.waitForTimeout(2000);\n`;
    } else if (action.type === 'click') {
      const sel = action.selector;
      // Password inputs are optional (extension may already be unlocked)
      if (sel.includes('password')) {
        test += `${indent}{ const _pw = ${target}.locator('${sel}').first(); if (await _pw.isVisible().catch(()=>false)) await _pw.click({ force: true, timeout: 5000 }); else console.log('[Wally] Skip password click not visible'); }\n`;
      } else       if (sel.startsWith('[data-testid=') || sel.startsWith('#') || sel.startsWith('[aria-label=')) {
        // data-testid clicks are often one-time (unlock, network switch) — make optional
        test += `${indent}{ const _el = ${target}.locator('${sel}').first(); if (await _el.isVisible().catch(()=>false)) await _el.click({ force: true, timeout: 5000 }); else console.log('[Wally] Skip not visible: ${sel}'); }\n`;
      } else if (sel.startsWith('button "') || sel.startsWith('link "')) {
        // Text-based selector — OK/Close/Cancel are often one-time modals, make optional
        const text = sel.match(/"(.+)"/)?.[1] || sel;
        const role = sel.split(' ')[0];
        const isOptional = /^(OK|Close|Cancel|Dismiss)$/i.test(text.trim());
        if (isOptional) {
          const v = `_btn${Math.random().toString(36).substring(2,4)}`;
          test += `${indent}{ const ${v} = ${target}.getByRole('${role}', { name: /${text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/i }).first(); if (await ${v}.isVisible().catch(()=>false)) await ${v}.click({ timeout: 5000 }); else console.log('[Wally] Skip optional button not visible: ' + ${JSON.stringify(text)}); }\n`;
        } else {
          const v2 = `_btn${Math.random().toString(36).substring(2,4)}`;
          test += `${indent}{ const ${v2} = ${target}.getByRole('${role}', { name: /${text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}/i }).first(); if (await ${v2}.isVisible().catch(()=>false)) { try { await ${v2}.click({ timeout: 10000 }); } catch(e) { console.log('[Wally] Click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip button not visible: ' + ${JSON.stringify(text)}); } }\n`;
        }
      } else if (sel.includes(' > ') || sel.includes(':nth-child') || sel.startsWith('div') || sel.startsWith('span') || sel.startsWith('p') || sel === 'html' || sel === 'body') {
        // CSS path (fallback nth-child) — fragile and often non-interactive (loading overlays, error messages)
        const text = action.text || '';
        const extensionKeywords = ['Ready', 'Argent', 'Braavos', 'Wallet', 'Carrot', 'STRK', 'Connect'];
        const isExtensionOption = extensionKeywords.some(k => text.includes(k));
        const isErrorOverlay = text.includes('Contrase') || text.includes('Loading') || text.includes('Bloq May') || text.includes('Desbloque');
        const isTextOnly = (sel === 'p' || sel.endsWith(' > p') || (sel.endsWith(' > span') && !sel.includes('button') && !sel.includes('a'))) && text.length > 15 && !isExtensionOption;
        if (isTextOnly || isErrorOverlay) {
          test += `${indent}// Skipped non-interactive: ${sel} "${text.substring(0, 40).replace(/'/g, "\\'").replace(/\n/g,' ')}"\n`;
        } else if (isExtensionOption && text) {
          const escText = text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').substring(0, 30);
          const varName = `_ext_${Math.random().toString(36).substring(2,6)}`;
          test += `${indent}{ const ${varName} = ${target}.getByText(/${escText}/i).first(); if (await ${varName}.isVisible().catch(()=>false)) { try { await ${varName}.click({ force: true, timeout: 10000 }); } catch(e) { console.log('[Wally] Extension click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip extension selector not visible: ' + ${JSON.stringify(escText)}); } }\n`;
        } else {
          // Robust: wait for visible with longer timeout for network/latency, skip if not found
          test += `${indent}{ const _el = ${target}.locator('${sel}').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): ${sel}'); } }\n`;
        }
      } else if (sel.startsWith('input[') || sel.startsWith('textarea[')) {
        // Input/textarea selectors — make optional (page may not have loaded, or name changed)
        test += `${indent}{ const _inp = ${target}.locator('${sel}').first(); if (await _inp.isVisible().catch(()=>false)) { try { await _inp.click({ force: true, timeout: 10000 }); } catch(e) { console.log('[Wally] Input click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip input not visible: ${sel}'); } }\n`;
      } else {
        test += `${indent}{ const _el = ${target}.locator('${sel}').first(); if (await _el.isVisible().catch(()=>false)) { try { await _el.click({ force: true, timeout: 10000 }); } catch(e) { console.log('[Wally] Click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip not visible: ${sel}'); } }\n`;
      }
      test += `${indent}await page.waitForTimeout(1000);\n`;
    } else if (action.type === 'fill') {
      const escaped = (action.value || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      // All fills are optional — page may not have loaded, or element may be transient
      test += `${indent}{ const _fill = ${target}.locator('${action.selector}').first(); if (await _fill.isVisible().catch(()=>false)) { try { await _fill.fill('${escaped}'); } catch(e) { console.log('[Wally] Fill failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip fill not visible: ${action.selector}'); } }\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'extension_connect') {
      const extensionType = action.extensionType || 'unknown';
      test += `${indent}// Extension connected: ${extensionType} (${action.account || 'unknown'})\n`;
      test += `${indent}await page.waitForTimeout(2000);\n`;
    } else if (action.type === 'select') {
      const escapedValue = (action.value || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      test += `${indent}await ${target}.selectOption('${action.selector}', '${escapedValue}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'press') {
      const key = (action.key || action.value || 'Enter').replace(/'/g, "\\'");
      test += `${indent}await ${target}.keyboard.press('${key}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'scroll') {
      const x = action.x || 0;
      const y = action.y || action.deltaY || 0;
      test += `${indent}await ${target}.evaluate(() => window.scrollBy(${x}, ${y}));\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'check') {
      test += `${indent}await ${target}.check('${action.selector}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'uncheck') {
      test += `${indent}await ${target}.uncheck('${action.selector}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'dblclick') {
      test += `${indent}await ${target}.dblclick('${action.selector}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'setInputFiles') {
      const filePath = (action.filePath || action.value || '/tmp/placeholder.txt').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
      test += `${indent}// WARNING: file path may not be valid — adjust as needed\n`;
      test += `${indent}await ${target}.setInputFiles('${action.selector}', '${filePath}');\n`;
      test += `${indent}await page.waitForTimeout(500);\n`;
    } else if (action.type === 'copy') {
      // Copy: select text on source element, then Ctrl+C
      const copyText = (action.text || '').replace(/'/g, "\\'").substring(0, 50);
      test += `${indent}// Copy: ${copyText}${action.text && action.text.length > 50 ? '...' : ''}\n`;
      test += `${indent}{ const _src = ${target}.locator('${action.selector}').first(); if (await _src.isVisible().catch(()=>false)) { try { await _src.click({ timeout: 5000 }); await ${target}.keyboard.press('Control+a'); await ${target}.keyboard.press('Control+c'); } catch(e) { console.log('[Wally] Copy failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip copy source not visible: ${action.selector}'); } }\n`;
      test += `${indent}await ${target}.waitForTimeout(500);\n`;
    } else if (action.type === 'paste') {
      // Paste: focus target element, then Ctrl+V
      const pasteText = (action.text || '').replace(/'/g, "\\'").substring(0, 50);
      test += `${indent}// Paste: ${pasteText}${action.text && action.text.length > 50 ? '...' : ''}\n`;
      test += `${indent}{ const _dst = ${target}.locator('${action.selector}').first(); if (await _dst.isVisible().catch(()=>false)) { try { await _dst.click({ timeout: 5000 }); await ${target}.keyboard.press('Control+v'); } catch(e) { console.log('[Wally] Paste failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip paste target not visible: ${action.selector}'); } }\n`;
      test += `${indent}await ${target}.waitForTimeout(500);\n`;
    } else {
      test += `${indent}// WARNING: unsupported action type '${action.type}' — skipped\n`;
    }

    // Close extension block if next action is on main page
    const nextAction = actions[actions.indexOf(action) + 1];
    const nextPage = nextAction ? (nextAction.page || 'main') : null;
    if (nextAction && lastPage.startsWith('ext:') && nextPage && !nextPage.startsWith('ext:')) {
      test += `  }\n\n`;
    }
  }

  // Close any open extension block
  if (lastPage.startsWith('ext:')) {
    test += `  }\n`;
  }

  test += `  console.log('[Wally] Replay done, final URL:', page.url());\n`;
  test += `  if (extPage) {\n`;
  test += `    console.log('[Wally] Extension final URL:', extPage.url());\n`;
  test += `    await extPage.bringToFront().catch(() => {});\n`;
  test += `  } else {\n`;
  test += `    await page.bringToFront().catch(() => {});\n`;
  test += `  }\n`;
  test += `  console.log('[Wally] Keeping browser open 10s for visual check...');\n`;
  test += `  await page.waitForTimeout(10000);\n`;
  test += `  await browser.close();\n`;
  test += `})().catch(e => { console.error(e); process.exit(1); });\n`;

  return test;
}

module.exports = { generatePlaywrightTest };
