/**
 * Auto-generated by Wally (built on libretto MIT primitives)
 * Recorded: 2026-09-04T09:37:40.347Z
 * Actions: 67
 * Pages: app.avnu.fi, unknown, ext:dlcobpji, x.cartridge.gg
 * Extension: detected (dlcobpji)
 * Run: node playwright.spec.js  (needs Chrome with --remote-debugging-port=9222 and Profile 9)
 */
const { chromium } = require('playwright');
const assert = require('assert');

const CDP_URL = 'http://127.0.0.1:9222';

(async () => {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const contexts = browser.contexts();
  const context = contexts.find(c => c.pages().length > 0) || contexts[0];
  let page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
  let extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));

    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});
  await page.goto('https://app.avnu.fi/en', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
  await page.waitForTimeout(2000);
  { const _wallet_lmke = page.getByText(/Connect a wallet/i).first(); if (await _wallet_lmke.isVisible().catch(()=>false)) { try { await _wallet_lmke.click({ force: true, timeout: 10000 }); } catch(e) { console.log('[Wally] Wallet click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip wallet selector not visible: ' + "Connect a wallet"); } }
  await page.waitForTimeout(1000);

    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});

    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});
  { const _wallet_cvbn = page.getByText(/Ready X/i).first(); if (await _wallet_cvbn.isVisible().catch(()=>false)) { try { await _wallet_cvbn.click({ force: true, timeout: 10000 }); } catch(e) { console.log('[Wally] Wallet click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip wallet selector not visible: ' + "Ready X"); } }
  await page.waitForTimeout(1000);

  // Switch to extension page (any chrome-extension:// URL)
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    // Wait for extension to open (triggered by prior page click)
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      console.log('[Wally] Waiting for extension popup...', i);
      await page.waitForTimeout(1000);
    }
  }
  if (!extPage) {
    console.log('[Wally] Extension not auto-opened, opening as tab...');
    extPage = await context.newPage();
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }
  if (extPage) {
    await extPage.bringToFront().catch(() => {});
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(1500);
    console.log('[Wally] Extension visible:', extPage.url());
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }


    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});
  { const _btnss = page.getByRole('button', { name: /OK/i }).first(); if (await _btnss.isVisible().catch(()=>false)) await _btnss.click({ timeout: 5000 }); else console.log('[Wally] Skip optional button not visible: ' + "OK"); }
  await page.waitForTimeout(1000);

  // Switch to extension page (any chrome-extension:// URL)
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    // Wait for extension to open (triggered by prior page click)
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      console.log('[Wally] Waiting for extension popup...', i);
      await page.waitForTimeout(1000);
    }
  }
  if (!extPage) {
    console.log('[Wally] Extension not auto-opened, opening as tab...');
    extPage = await context.newPage();
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }
  if (extPage) {
    await extPage.bringToFront().catch(() => {});
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(1500);
    console.log('[Wally] Extension visible:', extPage.url());
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/account/tokens', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
    { const _pw = extPage.locator('input[type="password"][name="password"]').first(); if (await _pw.isVisible().catch(()=>false)) await _pw.click({ force: true, timeout: 5000 }); else console.log('[Wally] Skip password click not visible'); }
    await page.waitForTimeout(1000);
    { const _fill = extPage.locator('input[type="password"][name="password"]').first(); if (await _fill.isVisible().catch(()=>false)) { try { await _fill.fill('MMOR4MORA!'); } catch(e) { console.log('[Wally] Fill failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip fill not visible: input[type="password"][name="password"]'); } }
    await page.waitForTimeout(500);
    { const _fill = extPage.locator('input[type="password"][name="password"]').first(); if (await _fill.isVisible().catch(()=>false)) { try { await _fill.fill('MMOR4MORA!'); } catch(e) { console.log('[Wally] Fill failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip fill not visible: input[type="password"][name="password"]'); } }
    await page.waitForTimeout(500);
    { const _el = extPage.locator('[data-testid="conectar-button"]').first(); if (await _el.isVisible().catch(()=>false)) await _el.click({ force: true, timeout: 5000 }); else console.log('[Wally] Skip not visible: [data-testid="conectar-button"]'); }
    await page.waitForTimeout(1000);
  }


    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});

  // Switch to extension page (any chrome-extension:// URL)
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    // Wait for extension to open (triggered by prior page click)
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      console.log('[Wally] Waiting for extension popup...', i);
      await page.waitForTimeout(1000);
    }
  }
  if (!extPage) {
    console.log('[Wally] Extension not auto-opened, opening as tab...');
    extPage = await context.newPage();
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }
  if (extPage) {
    await extPage.bringToFront().catch(() => {});
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(1500);
    console.log('[Wally] Extension visible:', extPage.url());
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }


    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});

    // Switch back to main page
    page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
    await page.bringToFront().catch(()=>{});
  { const _btnkh = page.getByRole('button', { name: /Bridge/i }).first(); if (await _btnkh.isVisible().catch(()=>false)) { try { await _btnkh.click({ timeout: 10000 }); } catch(e) { console.log('[Wally] Click failed (continuing):', e.message.split(String.fromCharCode(10))[0]); } } else { console.log('[Wally] Skip button not visible: ' + "Bridge"); } }
  await page.waitForTimeout(1000);
  await page.goto('https://app.avnu.fi/en/buy', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
  await page.waitForTimeout(2000);
  { const _el = page.locator('div:nth-child(2) > button > span').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): div:nth-child(2) > button > span'); } }
  await page.waitForTimeout(1000);
  { const _el = page.locator('div > div:nth-child(2) > span').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): div > div:nth-child(2) > span'); } }
  await page.waitForTimeout(1000);
  { const _el = page.locator('div > div:nth-child(2) > span').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): div > div:nth-child(2) > span'); } }
  await page.waitForTimeout(1000);
  { const _el = page.locator('div > div:nth-child(2) > span').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): div > div:nth-child(2) > span'); } }
  await page.waitForTimeout(1000);
  { const _el = page.locator('button > div > span').first(); if (await _el.isVisible().catch(()=>false)) { await _el.click({ force: true, timeout: 10000 }); } else { console.log('[Wally] Skip not visible (fragile): button > div > span'); } }
  await page.waitForTimeout(1000);
  console.log('[Wally] Replay done, final URL:', page.url());
  if (extPage) {
    console.log('[Wally] Extension final URL:', extPage.url());
    await extPage.bringToFront().catch(() => {});
  } else {
    await page.bringToFront().catch(() => {});
  }
  console.log('[Wally] Keeping browser open 10s for visual check...');
  await page.waitForTimeout(10000);
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
