/**
 * Auto-generated by Wally (built on libretto MIT primitives)
 * Recorded: 2026-09-04T09:37:40.347Z
 * Actions: 67
 * Pages: app.avnu.fi, unknown, ext:dlcobpji, x.cartridge.gg
 * Extension: detected (dlcobpji)
 * Run: node playwright.spec.js  (needs Chrome with --remote-debugging-port=9222 and Profile 9)
 */
const { chromium } = require('playwright');
const assert = require('assert');

const CDP_URL = 'http://127.0.0.1:9222';

(async () => {
  const browser = await chromium.connectOverCDP(CDP_URL);
  const contexts = browser.contexts();
  const context = contexts.find(c => c.pages().length > 0) || contexts[0];
  let page = context.pages().find(p => !p.url().startsWith('chrome-extension://')) || context.pages()[0];
  let extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  await page.goto('https://app.avnu.fi/en', { waitUntil: 'networkidle', timeout: 30000 });
  await page.waitForTimeout(3000);
  await page.getByText(/Connect a wallet/i).first().click({ timeout: 5000 });
  await page.waitForTimeout(1000);
  await page.getByText(/Ready X/i).first().click({ timeout: 5000 });
  await page.waitForTimeout(1000);

  // Switch to extension page (any chrome-extension:// URL)
  extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!extPage) {
    // Wait for extension to open (triggered by prior page click)
    for (let i = 0; i < 15; i++) {
      extPage = context.pages().find(p => p.url().startsWith('chrome-extension://'));
      if (extPage) break;
      console.log('[Wally] Waiting for extension popup...', i);
      await page.waitForTimeout(1000);
    }
  }
  if (!extPage) {
    console.log('[Wally] Extension not auto-opened, opening as tab...');
    extPage = await context.newPage();
    await extPage.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
    await extPage.waitForTimeout(2000);
  }
  if (extPage) {
    await extPage.bringToFront().catch(() => {});
    await extPage.waitForLoadState('domcontentloaded').catch(() => {});
    await extPage.waitForTimeout(1500);
    console.log('[Wally] Extension visible:', extPage.url());
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.getByRole('button', { name: /OK/i }).first().click({ timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/account/tokens', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.locator('input[type="password"][name="password"]').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('input[type="password"][name="password"]').fill('MMOR4MORA!');
    await page.waitForTimeout(500);
    await extPage.locator('input[type="password"][name="password"]').fill('MMOR4MORA!');
    await page.waitForTimeout(500);
    await extPage.locator('[data-testid="conectar-button"]').click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/index.html', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.getByRole('button', { name: /Bridge/i }).first().click({ timeout: 5000 });
    await page.waitForTimeout(1000);
    await page.goto('https://app.avnu.fi/en/buy', { waitUntil: 'networkidle', timeout: 30000 });
    await page.waitForTimeout(3000);
    await extPage.locator('div:nth-child(2) > button > span').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('div > div:nth-child(2) > span').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('div > div:nth-child(2) > span').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('div > div:nth-child(2) > span').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
    await extPage.locator('button > div > span').first().click({ force: true, timeout: 5000 });
    await page.waitForTimeout(1000);
  }
  console.log('[Wally] Replay done, final URL:', page.url());
  if (extPage) {
    console.log('[Wally] Extension final URL:', extPage.url());
    await extPage.bringToFront().catch(() => {});
  } else {
    await page.bringToFront().catch(() => {});
  }
  console.log('[Wally] Keeping browser open 10s for visual check...');
  await page.waitForTimeout(10000);
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
